baseurl = "https://www.bcsteaparty.com"
languageCode = "en-us"
title = "Bryan/College Station Texas Tea Party"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "wellokaythen"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-20501335-1"
theme = "hugo-minimalist-theme"
sectionPagesMenu = "main"

[markup.goldmark.renderer]
unsafe= true

[params]
    site_author = "B/CS Tea Party"
    site_description = "Teach. Empower. Act."
    location = "Bryan/College Station, Texas"
    # Link custom assets relative to /static
    avatar = "img/joinordie2.jpg"
    header_background = "img/bluebonnets.jpg"
    header_title = "Bryan/College Station Tea Party"
    copyright = "Bryan/College Station Tea Party. By the grace of God, powered by [Hugo](https://gohugo.io), [Github](https://github.com/), and [Netlify](https://www.netlify.com). Additional hat tip to the former [Lynda.com](https://www.lynda.com/)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "bcstp"
    gplus     = ""
