baseurl = "https://www.bcsteaparty.com/"
languageCode = "en-us"
title = "Bryan/College Station Texas Tea Party"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "wellokaythen"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "B/CS Tea Party"
    site_description = ""
    location = "Bryan/College Station, Texas"
    # Link custom assets relative to /static
    avatar = "img/joinordie2.jpg"
    header_background = "img/bluebonnets.jpg"
    header_title = "Bryan/College Station Tea Party"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "markcoppock"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "markcoppock"
    gplus     = ""
